/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tiles: Tile;
    collections: Collection;
    brands: Brand;
    ambients: Ambient;
    colors: Color;
    finishes: Finish;
    formats: Format;
    usages: Usage;
    rooms: Room;
    leads: Lead;
    'simulator-sessions': SimulatorSession;
    generations: Generation;
    'pdf-imports': PdfImport;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tiles: TilesSelect<false> | TilesSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    ambients: AmbientsSelect<false> | AmbientsSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    finishes: FinishesSelect<false> | FinishesSelect<true>;
    formats: FormatsSelect<false> | FormatsSelect<true>;
    usages: UsagesSelect<false> | UsagesSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'simulator-sessions': SimulatorSessionsSelect<false> | SimulatorSessionsSelect<true>;
    generations: GenerationsSelect<false> | GenerationsSelect<true>;
    'pdf-imports': PdfImportsSelect<false> | PdfImportsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Catálogo de azulejos del showroom. Solo se muestran al público los que están publicados.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tiles".
 */
export interface Tile {
  id: number;
  name: string;
  /**
   * Se usa en la URL: /catalogo/<slug>
   */
  slug: string;
  /**
   * Código interno o de marca.
   */
  sku?: string | null;
  description?: string | null;
  /**
   * Foto principal mostrada en listado y ficha.
   */
  mainImage: number | Media;
  /**
   * Imagen plana, tileable, en alta resolución. Se usa como referencia visual para la IA. Si está vacía, el simulador usará la imagen principal (peor resultado).
   */
  textureImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  collection?: (number | null) | Collection;
  brand?: (number | null) | Brand;
  colors?: (number | Color)[] | null;
  finish?: (number | null) | Finish;
  format?: (number | null) | Format;
  usages?: (number | Usage)[] | null;
  rooms?: (number | Room)[] | null;
  /**
   * Mostrado como referencia, nunca como precio firme. Vacío = "Consultar precio".
   */
  orientativePrice?: number | null;
  priceUnit?: ('m2' | 'unit' | 'box') | null;
  published?: boolean | null;
  featured?: boolean | null;
  /**
   * Marcar solo cuando la textura ha sido validada visualmente con buenos resultados en el simulador.
   */
  aiReady?: boolean | null;
  /**
   * Campos libres: espesor, rectificado, PEI, antideslizante, etc.
   */
  attributesJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  name: string;
  slug: string;
  brand?: (number | null) | Brand;
  description?: string | null;
  coverImage?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  name: string;
  /**
   * Identificador para URLs y filtros (ej: blanco-marfil).
   */
  slug: string;
  /**
   * Color hex para el swatch (#RRGGBB).
   */
  hex?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishes".
 */
export interface Finish {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formats".
 */
export interface Format {
  id: number;
  /**
   * Ejemplo: 60x60, 30x90, hexagonal 25.
   */
  name: string;
  slug: string;
  widthCm?: number | null;
  heightCm?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tipo de uso recomendado (suelo interior, pared baño, exterior...).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usages".
 */
export interface Usage {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Estancias para clasificar y filtrar el catálogo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fotos inspiracionales de estancias con azulejos aplicados.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ambients".
 */
export interface Ambient {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  image: number | Media;
  tilesUsed?:
    | {
        tile: number | Tile;
        surface?: ('floor' | 'wall' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  roomType?: (number | null) | Room;
  /**
   * Ej: nórdico, industrial, mediterráneo...
   */
  style?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contactos comerciales captados desde la web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  /**
   * Se calcula automáticamente con el nombre o el contacto.
   */
  displayName?: string | null;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  sqMeters?: number | null;
  dontKnowSqm?: boolean | null;
  comment?: string | null;
  preferredChannel?: ('whatsapp' | 'email' | 'phone') | null;
  source?: ('simulator' | 'product_page' | 'footer' | 'contact_page') | null;
  tileOfInterest?: (number | null) | Tile;
  /**
   * Imagen generada por IA asociada a este lead, si la hay.
   */
  generationImageUrl?: string | null;
  /**
   * Identificador de la sesión temporal del usuario.
   */
  sessionId?: string | null;
  status?: ('new' | 'contacting' | 'won' | 'lost' | 'discarded') | null;
  consentAccepted?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sesiones temporales de usuarios anónimos del simulador. Se borran automáticamente al expirar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulator-sessions".
 */
export interface SimulatorSession {
  id: number;
  /**
   * 64 hex chars. Equivale a un secreto compartido con el cliente.
   */
  token: string;
  generationCount?: number | null;
  expiresAt: string;
  /**
   * Se rellena si la sesión llega a conversión.
   */
  lead?: (number | null) | Lead;
  /**
   * IP hash, user agent, etc. (no PII directa).
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cada simulación generada por IA. Vinculada a una sesión y a un azulejo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generations".
 */
export interface Generation {
  id: number;
  session: number | SimulatorSession;
  tile: number | Tile;
  surfaces: ('floor' | 'wall')[];
  /**
   * Si se cambia el color de la pared no cubierta por azulejos.
   */
  wallColor?: string | null;
  userImage: number | Media;
  resultImage?: (number | null) | Media;
  status: 'queued' | 'processing' | 'completed' | 'failed';
  /**
   * ej: openai:gpt-image-1
   */
  providerUsed?: string | null;
  /**
   * Para auditoría y mejora iterativa.
   */
  promptUsed?: string | null;
  costCents?: number | null;
  latencyMs?: number | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sube un catálogo en PDF de un proveedor y conviértelo automáticamente en azulejos de tu catálogo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf-imports".
 */
export interface PdfImport {
  id: number;
  /**
   * Se calcula automáticamente con el nombre del fichero y la marca.
   */
  displayName?: string | null;
  /**
   * Sube el catálogo en PDF del proveedor.
   */
  originalFile: number | Media;
  /**
   * Opcional. Si no se indica, intentaremos detectarla automáticamente del propio PDF.
   */
  brand?: (number | null) | Brand;
  /**
   * Rango de páginas a procesar.
   */
  pageRangeFrom?: number | null;
  /**
   * Dejar vacío para procesar hasta el final.
   */
  pageRangeTo?: number | null;
  /**
   * Hard cap de páginas a procesar en esta ejecución (control de coste). Sube cuando confirmes calidad.
   */
  maxPages?: number | null;
  status?: ('queued' | 'processing' | 'review_ready' | 'importing' | 'completed' | 'failed') | null;
  totalPages?: number | null;
  processedPages?: number | null;
  progressPercent?: number | null;
  /**
   * Lo que el worker está haciendo ahora mismo.
   */
  currentStep?: string | null;
  candidatesCount?: number | null;
  /**
   * Array de candidatos JSON: cada elemento es un azulejo identificado con su info y estado de revisión (pending/accepted/rejected). Editable desde la vista de revisión.
   */
  extractedItems?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorMessage?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * Azulejos generados al publicar los aceptados.
   */
  createdTiles?: (number | Tile)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tiles';
        value: number | Tile;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'ambients';
        value: number | Ambient;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'finishes';
        value: number | Finish;
      } | null)
    | ({
        relationTo: 'formats';
        value: number | Format;
      } | null)
    | ({
        relationTo: 'usages';
        value: number | Usage;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'simulator-sessions';
        value: number | SimulatorSession;
      } | null)
    | ({
        relationTo: 'generations';
        value: number | Generation;
      } | null)
    | ({
        relationTo: 'pdf-imports';
        value: number | PdfImport;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tiles_select".
 */
export interface TilesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sku?: T;
  description?: T;
  mainImage?: T;
  textureImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  collection?: T;
  brand?: T;
  colors?: T;
  finish?: T;
  format?: T;
  usages?: T;
  rooms?: T;
  orientativePrice?: T;
  priceUnit?: T;
  published?: T;
  featured?: T;
  aiReady?: T;
  attributesJson?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  brand?: T;
  description?: T;
  coverImage?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ambients_select".
 */
export interface AmbientsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  tilesUsed?:
    | T
    | {
        tile?: T;
        surface?: T;
        id?: T;
      };
  roomType?: T;
  style?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  hex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishes_select".
 */
export interface FinishesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formats_select".
 */
export interface FormatsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  widthCm?: T;
  heightCm?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usages_select".
 */
export interface UsagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  displayName?: T;
  name?: T;
  phone?: T;
  email?: T;
  sqMeters?: T;
  dontKnowSqm?: T;
  comment?: T;
  preferredChannel?: T;
  source?: T;
  tileOfInterest?: T;
  generationImageUrl?: T;
  sessionId?: T;
  status?: T;
  consentAccepted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulator-sessions_select".
 */
export interface SimulatorSessionsSelect<T extends boolean = true> {
  token?: T;
  generationCount?: T;
  expiresAt?: T;
  lead?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generations_select".
 */
export interface GenerationsSelect<T extends boolean = true> {
  session?: T;
  tile?: T;
  surfaces?: T;
  wallColor?: T;
  userImage?: T;
  resultImage?: T;
  status?: T;
  providerUsed?: T;
  promptUsed?: T;
  costCents?: T;
  latencyMs?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf-imports_select".
 */
export interface PdfImportsSelect<T extends boolean = true> {
  displayName?: T;
  originalFile?: T;
  brand?: T;
  pageRangeFrom?: T;
  pageRangeTo?: T;
  maxPages?: T;
  status?: T;
  totalPages?: T;
  processedPages?: T;
  progressPercent?: T;
  currentStep?: T;
  candidatesCount?: T;
  extractedItems?: T;
  errorMessage?: T;
  startedAt?: T;
  completedAt?: T;
  createdTiles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Datos de marca, contacto y contenidos editables. Todo es configurable sin tocar código.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  /**
   * Formato internacional sin signos: ej. 34600000000. Usado para wa.me/<numero>.
   */
  whatsappNumber?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  openingHours?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  aboutShort?: string | null;
  companyLegalName?: string | null;
  companyCif?: string | null;
  privacyPolicyUrl?: string | null;
  cookiesPolicyUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  whatsappNumber?: T;
  phone?: T;
  email?: T;
  address?: T;
  openingHours?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  aboutShort?: T;
  companyLegalName?: T;
  companyCif?: T;
  privacyPolicyUrl?: T;
  cookiesPolicyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}